### ISSUE TITLE
Create a Mark folder and create a custom readme.md for it

### ISSUE THREAD

**Issue by docligot** [docligot/guided_internship#2]
Hi mark - create your own folder and create a custom readme.md for it

**Comment by Mr-Miaral** [comment]
Hi Doc ! where should I create the folder ?

**Comment by docligot** [comment]
First - create a new branch on the repository
Next - create a folder called 'Mark' in the directory
Lastly - create a file called readme.md and fill it up with anything
Commit and Push
Then do a pull request

**Comment by docligot** [comment]
Closing this issue.
